pipeline {
    agent any
    stages {
         stage('Checkout') {
            steps {
                git 'https://github.com/sivakrishna1818/JAVA_PIPELINE.git'
            }
        stage('Build') {
            steps {
               sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
